### ISSUE TITLE
LXD doesnt honor docker-image variable

### ISSUE THREAD

**Issue by itayo** [erik78se/operator-gitlab-runner#3]
Currently, the runner doesn't honor the docker-image variable to set it into its configuration when running LXD.

**Comment by itayo** [comment]
also we could probably rename this field to Image only as it is for both

**Comment by itayo** [comment]
@erik78se  is it ok if we rename it to Image instead of docker-image?

**Comment by erik78se** [comment]
Introduce lxd-image instead which could also include a working default and
better description

Den tis 1 juni 2021 13:08Stefan Nygren ***@***.***> skrev:

**Comment by erik78se** [comment]
It turns out that this is achieved by using the "image" keyword in the .gitlab-ci.yaml OR the CUSTOM_ENV_CI_JOB_IMAGE in the project settings in gitlab which you can set for the runner.

It can possibly be introduced as some custom setting, but I've added some documentation to README.md how to achieve a custom image for lxd.
